# Generated by Django 3.0.6 on 2020-05-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('upload_date', models.DateField()),
                ('main_image', models.ImageField(upload_to='main_images/')),
                ('heart', models.IntegerField(default=0)),
            ],
        ),
    ]
