# Generated by Django 3.0.1 on 2020-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
