# Generated by Django 3.0.1 on 2020-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='main_image',
            field=models.ImageField(upload_to='app_images/'),
        ),
    ]
