# Generated by Django 3.0.1 on 2020-05-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200505_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='content',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
