# Generated by Django 3.0.1 on 2020-04-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('upload_date', models.DateField()),
                ('main_image', models.ImageField(upload_to='media/main_images/')),
            ],
        ),
    ]
