# Generated by Django 3.0.1 on 2020-04-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='main_image',
            field=models.ImageField(upload_to='main_images/'),
        ),
    ]
