# Generated by Django 3.0.1 on 2020-05-03 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_wallpaper_wallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(blank=True, choices=[('iph7', 'Iphone 7'), ('iph8', 'Iphone 8'), ('iph11p', 'Iphone 11 Pro'), ('iph11', 'Iphone 11'), ('iphXS', 'Iphone X/XS'), ('iphXR', 'Iphone XR'), ('samZ', 'Samsung Z Flip'), ('sams20', 'Samsung S20'), ('sams20+', 'Samsung S20+'), ('ipadp10.5', 'iPad Pro 10.5-inch'), ('ipadp12.9', 'iPad Pro 12.9-inch'), ('no14', '14 Notebook'), ('no15.6', '15.6 Notebook'), ('nomacp13', 'Macbook Pro 13'), ('nomacp16', 'Macbook Pro 16'), ('3821', '3840*2160'), ('2516', '2560*1600'), ('2514', '2560*1440'), ('2015', '2048*1536'), ('1914', '1920*1440'), ('1912', '1920*1200'), ('1910', '1920*1080'), ('1610', '1680*1050'), ('1612', '1600*1200'), ('1690', '1600*900'), ('1490', '1440*900'), ('6676', '1366*768'), ('6076', '1360*768'), ('1210', '1280*1024'), ('1296', '1280*960')], max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallpaper.Wallpaper')),
            ],
        ),
    ]
